name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: "Force HTTPS"
      run: git config --global url."https://github".insteadOf ssh://git@github
    - name: "Checkout sources"
      uses: actions/checkout@v4
    - name: "Setup NodeJS"
      uses: actions/setup-node@v3
      with:
        node-version: "20.x"
    - name: "Install dependencies"
      run: npm ci
    - name: "Build"
      run: npm run build --if-present
    - name: "Run tests"
      run: npm test
